[versions]
# Minecraft
paper = "1.18.1-R0.1-SNAPSHOT"

# Gradle plugins
publish = "0.35.0"

[libraries]
paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }

[plugins]
publish = { id = "com.vanniktech.maven.publish", version.ref = "publish" }
